module.exports = {
  projects: [
    '<rootDir>/libs/lib1',
    '<rootDir>/libs/lib2',
    '<rootDir>/apps/demo',
    '<rootDir>/libs/lib3',
    '<rootDir>/libs/lib4',
    '<rootDir>/libs/lib5',
    '<rootDir>/libs/lib6',
    '<rootDir>/libs/lib7',
    '<rootDir>/libs/lib8',
    '<rootDir>/libs/lib9',
    '<rootDir>/libs/lib10',
    '<rootDir>/libs/lib11',
    '<rootDir>/libs/lib12',
    '<rootDir>/libs/lib13',
    '<rootDir>/libs/lib14',
    '<rootDir>/libs/lib15',
    '<rootDir>/libs/lib16',
    '<rootDir>/apps/demo2',
    '<rootDir>/apps/demo3',
    '<rootDir>/apps/demo4',
  ],
};
